First iteration of generated systems documentation.

diff --git a/config/functions b/config/functions
--- a/config/functions
+++ b/config/functions
@@ -1764,6 +1764,67 @@ exec_thread_safe() {
   return ${result}
 }
 
+### Generate System Documentation
+
+clean_doc_cache() {
+  DOCTMP="${ROOT}/.doc_cache/${DEVICE}"
+  if [ -d "${DOCTMP}" ]
+  then
+    rm -rf "${DOCTMP}"
+  fi
+}
+
+start_system_doc() {
+  if [ -z "${SYSDOC}" ]
+  then
+    echo "Unable to generate documentation, define SYSDOC in options."
+    exit 1
+  fi
+  if [ -e "${SYSDOC}" ]
+  then
+    rm -f ${SYSDOC}
+  fi
+  if [ -e "${ROOT}/templates/${SYSDOCROOT}.md" ]
+  then
+    cp ${ROOT}/templates/${SYSDOCROOT}.md ${SYSDOC}
+  fi
+  cat <<EOF >>${SYSDOC}
+## Supported Systems, Emulators, and Cores for ${DEVICE}
+
+|Manufacturer|System|Release Date|Games Path|Supported Extensions|Emulator / Core|
+|----|----|----|----|----|----|
+EOF
+}
+
+add_system_doc() {
+  cat <<EOF >>${DOCTMP}/${1}:system.tmp
+|${SYSTEM_MANUFACTURER}|${SYSTEM_FULLNAME} (${SYSTEM_NAME})|${SYSTEM_RELEASE}|${SYSTEM_PATH}|${SYSTEM_EXTENSION}||
+EOF
+}
+
+add_emu_doc() {
+  if [ ! -d "${DOCTMP}" ]
+  then
+    mkdir -p "${DOCTMP}"
+  fi
+  cat <<EOF >>${DOCTMP}/${1}:emulators.tmp
+|||||${2}: ${3}|
+EOF
+}
+
+mk_system_doc() {
+  for system in $(ls ${DOCTMP}/ | awk 'BEGIN {FS=":"} {print $1}' | sort | uniq)
+  do
+    cat ${DOCTMP}/${system}:system.tmp >>${SYSDOC}
+    if [ -e "${DOCTMP}/${system}:emulators.tmp" ]
+    then
+      cat ${DOCTMP}/${system}:emulators.tmp >>${SYSDOC}
+    fi
+  done
+}
+
+### Generate ES Systems
+
 clean_es_cache() {
   ESTMP="${ROOT}/.es_cache/${DEVICE}"
   if [ -d "${ESTMP}" ]
@@ -1780,9 +1841,11 @@ add_emu_core() {
 
   # Schema: emulator|core|true/false
   echo "${2}|${3}|${4}" >>${ESTMP}/${1}-emulators.tmp
+  add_emu_doc $*
 }
 
 mk_es_systems() {
+
   cat <<EOF >${ESTMP}/.es_systems.cfg
 <?xml version="1.0" encoding="UTF-8"?>
 <systemList>
@@ -1796,6 +1859,7 @@ EOF
 </systemList>
 EOF
 xmlstarlet fo -t ${ESTMP}/.es_systems.cfg >${ESTMP}/es_systems.cfg 2>/dev/null
+
 } 
 
 add_system_dir() {
@@ -1895,7 +1959,7 @@ EOF
       fi
     done <${ESTMP}/${SYSTEM_NAME}-emulators.tmp
   fi
-
+  add_system_doc ${SYSTEM_NAME}
 }
 
 # Use distribution functions if any
