Additional merged storage optimizations, add a script to remove empty directories that may cause overlay issues.

diff --git a/packages/jelos/sources/scripts/automount b/packages/jelos/sources/scripts/automount
--- a/packages/jelos/sources/scripts/automount
+++ b/packages/jelos/sources/scripts/automount
@@ -5,46 +5,55 @@
 . /etc/profile
 . /etc/os-release
 
+### Vars
 UPDATE_ROOT="/storage/.update"
 MOUNT_GAMES=$(get_setting system.automount)
 GAMES_DEVICE=$(get_setting system.gamesdevice)
-
 MS_ENABLED=$(get_setting system.merged.storage)
 MS_DEVICE=$(get_setting system.merged.device)
+
+
+### Default to the external storage device.
+MOUNT_PATH="/storage/games-external"
+
 MS_PATH="/storage/roms"
-if [ -z "${MS_DEVICE}" ]
-then
-  MS_DEVICE="external"
-fi
-MOUNT_PATH="/storage/games-${MS_DEVICE}"
+
+function unmount() {
+  NULL=$(grep -e "${1}" /proc/mounts >/dev/null 2>&1)
+  if [ "$?" = "0" ]
+  then
+    log $0 "Unmount ${1}."
+    umount -f "${1}" 2>/dev/null ||:
+  fi
+}
 
 function start_ms() {
+  ### Entrypoint will be either games card found (external), or not found (internal).
+  MOUNT_PATH="/storage/games-${1}"
+
+  unmount ${MS_PATH}
+
+  ### Determine if internal or external is the primary target by configuration.
+  case ${MS_DEVICE} in
+    internal)
+      LOWER="internal"
+      UPPER="external"
+    ;;
+    *)
+      LOWER="external"
+      UPPER="internal"
+    ;;
+  esac
+
   if [ -e "/storage/.ms_unsupported" ] || \
-     [ "${MS_ENABLED}" = "false" ]
+     [ "${MS_ENABLED}" = 0 ]
   then
-    # If we're not using merged storage, bind mount the external storage path
-    # so we don't need to change any configs.
-    grep ${MOUNT_PATH} /proc/mounts >/dev/null 2>&1
-    if [ ! $? = 0 ]
-    then
-      MOUNT_PATH="/storage/games-internal"
-    fi
     log $0 "Executing bind mount of ${MOUNT_PATH} to ${MS_PATH}"
     mount --bind ${MOUNT_PATH}/roms ${MS_PATH}
     exit 0
   else
-    log $0 "Enabling merged storage."
+    log $0 "Enabling merged storage of /storage/games-${LOWER} and /storage/games-${UPPER} to ${MS_PATH}."
 
-    case ${MS_DEVICE} in
-      internal)
-        LOWER="internal"
-        UPPER="external"
-      ;;
-      *)
-        LOWER="external"
-        UPPER="internal"
-      ;;
-    esac
     for DIR in /storage/games-${UPPER}/.tmp/games-workdir /storage/games-${LOWER}/roms /storage/games-${UPPER}/roms
     do
       if [ ! -d "${DIR}" ]
@@ -52,7 +61,7 @@ function start_ms() {
         mkdir -p "${DIR}"
       fi
     done
-    mount overlay -t overlay -o lowerdir=/storage/games-${LOWER}/roms,upperdir=/storage/games-${UPPER}/roms,workdir=/storage/games-${UPPER}/.tmp/games-workdir /storage/roms
+    mount overlay -t overlay -o lowerdir=/storage/games-${LOWER}/roms,upperdir=/storage/games-${UPPER}/roms,workdir=/storage/games-${UPPER}/.tmp/games-workdir ${MS_PATH}
   fi
 }
 
@@ -61,16 +70,12 @@ then
   set_setting system.automount 1
 elif [[ "${MOUNT_GAMES}" == "0" ]]
 then
-  start_ms
+  start_ms internal
   exit 0
 fi
 
-function unmount_roms() {
-  NULL=$(cat /proc/mounts | grep -v -e "${MS_PATH}" 2>/dev/null | grep ${1})
-  if [ ! "$?" = "0" ]
-  then
-    umount -f "${MS_PATH}"
-  fi
+function create_game_dirs() {
+  systemd-tmpfiles --create /usr/lib/tmpfiles.d/JELOS-system-dirs.conf >/dev/null 2>&1 ||:
 }
 
 function load_modules() {
@@ -86,7 +91,7 @@ function load_modules() {
 }
 
 function mount_games() {
-      unmount_roms
+      local MOUNT_PATH="/storage/games-external"
       FSTYPE=$(blkid -o export ${1} | awk 'BEGIN {FS="="} /TYPE/ {print $2}')
       case ${FSTYPE} in
         ext4)
@@ -96,7 +101,6 @@ function mount_games() {
             rm -f /storage/.ms_unsupported
           fi
 	  touch /storage/.ms_supported
-          set_setting system.merged.storage 1
         ;;
         *)
           log $0 "Partition does not support overlayfs, disabling."
@@ -119,14 +123,18 @@ function mount_games() {
          [ -e "${1}" ] && \
          [ ! -e "/storage/.please_resize_me" ]
       then
+
         ### Udevil shouldn't mount it this early, but just in-case.
         umount /var/media/* 2>/dev/null
+
         log $0 "Checking filesystem ${1}."
         fsck -Mly ${1} >/dev/null 2>&1
+
         log $0 "Mounting ${1} on ${MOUNT_PATH}"
         /usr/bin/busybox mount ${1} ${MOUNT_PATH} >/dev/null 2>&1
       fi
-      start_ms
+      start_ms external
+      create_game_dirs
       exit 0
 }
 
@@ -160,12 +168,17 @@ function find_games() {
         break
       fi
     done
-    # If we're here there is no external storage to use, but we want to start merged storage or the bind mount anyway.
-    start_ms
+    log $0 "Could not find external card to mount, assume internal."
+    start_ms internal
   fi
 }
 
+## Main..
+
 load_modules
+
+### Unmount external storage if it's mounted.
+unmount "${MOUNT_PATH}"
 
 if [ -e "${GAMES_DEVICE}" ]
 then
