Revert "Drop x86 from dev."
This reverts commit 860d44743d7a672bf2fb0dc49ed000cf0107f369.

diff --git a/scripts/build_compat b/scripts/build_compat
--- a/scripts/build_compat
+++ b/scripts/build_compat
@@ -116,7 +116,7 @@ for directory in etc dev proc run sys tmp usr var flash storage; do
   mkdir -p ${INSTALL}/${directory}
 done
 
-MTADDONBUILD=no start_multithread_build arm32 || die "Parallel build failure - see log for details. Time of failure: $(date)"
+MTADDONBUILD=no start_multithread_build ${1} || die "Parallel build failure - see log for details. Time of failure: $(date)"
 echo "Successful build!  Building compatibility root..." >&2
 exit 0
 
